info:
  version: 1.0.3
  description: AUSF config

configuration:
  sbi:
    scheme: http
    registerIPv4: 10.100.200.14
    bindingIPv4: 10.100.200.14
    port: 8000
    tls:
      pem: cert/ausf.pem
      key: cert/ausf.key
  serviceNameList:
    - nausf-auth
  nrfUri: http://10.100.200.10:8000
  nrfCertPem: cert/nrf.pem
  plmnSupportList:
    - mcc: 208
      mnc: 93
  groupId: ausfGroup001

logger:
  enable: true
  level: info
  reportCaller: false
